### ISSUE TITLE
No Prev/next hotbar bind

### ISSUE THREAD

**Issue by GrubPL** [19Phin/Questbinding#1]
ok so either i am blind, or this just dosent exist yet but i guess its a really big issue, considering questcraft has them binded, trying to rebind place to the grip is sure goin to be an issue without messin with files, or like i said, i am just super blind

**Comment by DialingSpoon527** [comment]
It should? I've done it before.

**Comment by DialingSpoon527** [comment]
It's possible vivecraft removed it, but I haven't done anything

**Comment by DialingSpoon527** [comment]
ah, yes Vivecraft hid their VR keybinds in the newest version, good catch.

**Comment by DialingSpoon527** [comment]
has been fixed.
