### ISSUE TITLE
Compatibility with Create Mod and Scroll Functionality on Controller

### ISSUE THREAD

**Issue by Teralink** [19Phin/Questbinding#2]
Hi,

First of all, thank you for the amazing work on the Questbinding mod!

I’m currently trying to use your mod alongside the Create mod, but I’m having an issue. In Create, scrolling is required to select values in some popups. However, I can’t seem to map mouse scrolling to a button on my controllers (left stick press > scroll down) using Questbinding – it just doesn’t seem to do anything, even after a restart.

Is Questbinding known to be compatible with Create, and if so, is there a specific way to set up the scroll functionality on a controller?

Any help would be greatly appreciated!

**Comment by DialingSpoon527** [comment]
Unfortunately no, mods with unbindable controls like that are usually hardcoded to search for keybind input.
I looked into a way to make the quest controllers directly simulate keyboard input for a while, but it was getting annoying and I got distracted. I may come back to it in the future. But sorry to say don't expect it anytime soon.

**Comment by Teralink** [comment]
Thanks for the quick reply! Totally get that hardcoded controls are tricky. No worries – I’ll look into external tools for a workaround. If you ever get back to it, I’d love to try it out!
